-- Adding games to games
-- INSERT INTO games(game_title, year_released, game_cover_path, game_desc) VALUES
--     
--     (
--     "The Legend of Zelda: Tears of the Kingdom", 
--     2023, 
--     "/static/coverimages/tloz-totk.jpg", 
--     "In this sequel to the Legend of Zelda: Breath of the Wild game, you’ll decide your own path through the sprawling landscapes of Hyrule and the mysterious islands floating in the vast skies above. Can you harness the power of Link’s new abilities to fight back against the malevolent forces that threaten the kingdom?"
--     ),
-- 
--     (
--     "Minecraft",
--     2009,
--     "/static/coverimages/minecraft.jpg",
--     "Build anything you can imagine, uncover eerie mysteries, and survive the night in the ultimate sandbox game. In Minecraft, every playthrough is different, and unforgettable adventures await behind every corner. Explore and craft your way through an infinite world that’s yours to shape, one block at a time."
--     ),
-- 
--     (
--     "Elden Ring",
--     2022,
--     "/static/coverimages/elden-ring.jpg",
--     "Journey through the Lands Between, a new fantasy world created by Hidetaka Miyazaki, creator of the influential DARK SOULS video game series, and George R. R. Martin, author of The New York Times best-selling fantasy series, A Song of Ice and Fire."
--     ),
-- 
--     (
--     "Hollow Knight",
--     2017,
--     "/static/coverimages/hollow-knight.jpg",
--     "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."
--     ),
-- 
--     (
--     "Genshin Impact",
--     2020,
--     "/static/coverimages/genshin-impact.jpg",
--     "Embark on a journey across Teyvat to find your lost sibling and seek answers from The Seven — the gods of each element. Explore this wondrous world, join forces with a diverse range of characters, and unravel the countless mysteries that Teyvat holds..."
--     ),
-- 
--     (
--     "Subnautica",
--     2018,
--     "/static/coverimages/subnautica.png",
--     "Descend into the depths of an alien underwater world filled with wonder and peril. Craft equipment, pilot submarines and out-smart wildlife to explore lush coral reefs, volcanoes, cave systems, and more - all while trying to survive."
--     );

-- INSERT INTO games(game_title, year_released, game_cover_path, game_desc) VALUES
--     
--     (
--     "VALORANT",
--     2020, 
--     "/static/coverimages/valorant.jpg", 
--     "VALORANT is a character-based 5v5 tactical shooter set on the global stage. Outwit, outplay, and outshine your competition with tactical abilities, precise gunplay, and adaptive teamwork."
--     );

-- INSERT INTO games(game_title, year_released, game_cover_path, game_desc) VALUES
-- 
--     (
--     "Pico Park",
--     2016,    
--     "/static/coverimages/pico-park.jpg",
--     "PICO PARK is a cooperative local/online multiplay action puzzle game for 2-8 players. The rule is quite simple: Get all the keys and get to the goal and clear, but all 48 levels have special gimmicks designed specifically for multiplayer."
--     ),
-- 
--     (
--     "Muck",
--     2021,
--     "/static/coverimages/muck.jpg",
--     "Muck is a survival-roguelike. Collect resources, find items & build a base to survive for as long as you can."
--     );
-- INSERT INTO games(game_title, year_released, game_cover_path, game_desc) VALUES
-- 
--     (
--     "Block Blast!",
--     2022,
--     "/static/coverimages/block-blast.jpg",
--     "Block Blast is a free and popular block puzzle game that is your best choice when you want to pass the casual time and challenge your brain. The goal of this block puzzle game is easy yet fun: match and clear as many colored blocks as possible on the board."
--     );
